from bar.models import Counter, Beer, Membership
from django.db.models import F

Counter.objects.all()
Beer.objects.all()
Membership.objects.all()

Beer.objects.all().delete()
polar = Beer.objects.create(name = 'polar')
zulia = Beer.objects.create(name = 'zulia')
solera = Beer.objects.create(name = 'solera')
polar.save()
zulia.save()
solera.save()
Beer.objects.all()

Counter.objects.all().delete()
teatro = Counter.objects.create(name = 'teatro')
trasnocho = Counter.objects.create(name = 'trasnocho')
tolon = Counter.objects.create(name = 'tolon')
teatro.save()
trasnocho.save()
tolon.save()
Counter.objects.all()

Membership.objects.all().delete()
m = Membership(beer=polar, counter=teatro, availability=13)
m.save()
m = Membership(beer=zulia, counter=teatro, availability=16)
m.save()
m = Membership(beer=solera, counter=teatro, availability=19)
m.save()
m = Membership(beer=polar, counter=trasnocho, availability=113)
m.save()
m = Membership(beer=zulia, counter=trasnocho, availability=116)
m.save()
m = Membership(beer=solera, counter=trasnocho, availability=119)
m.save()
m = Membership(beer=polar, counter=tolon, availability=1113)
m.save()
m = Membership(beer=zulia, counter=tolon, availability=1116)
m.save()
m = Membership(beer=solera, counter=tolon, availability=1119)
m.save()
Membership.objects.filter(beer=polar, counter=teatro).update(availability=F('availability')+10)
Membership.objects.filter(beer=zulia, counter=teatro).update(availability=F('availability')+10)
Membership.objects.filter(beer=solera, counter=teatro).update(availability=F('availability')+10)
Membership.objects.all()
